services:
  lb:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-local
    command:
      - /lb
    environment:
      LB_PORT: "9999"
      LB_SOCKET: /sockets/lb.sock
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    restart: unless-stopped

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-local
    command:
      - /server
    environment:
      LB_SOCKET: /sockets/lb.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - lb
    restart: unless-stopped

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    image: rinha-local
    command:
      - /server
    environment:
      LB_SOCKET: /sockets/lb.sock
    volumes:
      - sockets:/sockets
    depends_on:
      - lb
    restart: unless-stopped

volumes:
  sockets: