x-common: &common
  build:
    context: .
    dockerfile: Dockerfile
  image: rinha-local
  volumes:
    - sockets:/sockets
  restart: unless-stopped

services:
  lb:
    container_name: rinha-lb
    <<: *common
    command:
      - /lb
    environment:
      LB_PORT: "8080"
      LB_SOCKET: /sockets/lb.sock
    ports:
      - "9999:8080"

  workers:
    container_name: rinha-workers
    <<: *common
    command:
      - /server
    environment:
      LB_SOCKET: /sockets/lb.sock
      WORKERS_AMOUNT: 2
    depends_on:
      - lb

volumes:
  sockets:
    name: rinha-volume